# Generated by Django 3.2 on 2023-01-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greatestinvestapp', '0004_auto_20230114_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='email',
        ),
        migrations.AddField(
            model_name='bonus',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
