# Generated by Django 3.2 on 2023-01-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greatestinvestapp', '0005_auto_20230120_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='client_email',
            field=models.CharField(blank=True, max_length=68, null=True),
        ),
    ]
