# Generated by Django 3.2 on 2023-01-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greatestinvestapp', '0007_alter_bonus_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal_request',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
